/*   ==================================================================

	 >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
	 ------------------------------------------------------------------
	 Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
	 ALL RIGHTS RESERVED
	 ------------------------------------------------------------------

	   IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
	   DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

	   Lattice grants permission to use this code pursuant to the
	   terms of the Lattice Propel License Agreement.

	 DISCLAIMER:

	LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
	WHETHER EXPRESSED, IMPLIED, STATUTORY,
	OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
	COMMUNICATION WITH LICENSEE,
	AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
	MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
	LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
	LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
	SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
	UNINTERRUPTED OR ERROR FREE,
	OR THAT DEFECTS HEREIN WILL BE CORRECTED.
	LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
	ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
	AND RESULTS OBTAINED THEREFROM.
	LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
	DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
	LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
	CORRECTION,
	OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
	SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
	INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
	INCLUDING LOST PROFITS,
	ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
	EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
	LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
	IS SET FORTH ABOVE.
	LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
	ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
	INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
	RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
	FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
	 ------------------------------------------------------------------

	 ================================================================== */

#ifndef __GPIO__
#define __GPIO__

#include "gard_types.h"

#define GPIO_DRV_VER       "v1.6.2"

// #define _DIRECTION_INTERNAL_MEMORY_USE_
#define MAX_NUMBER_OF_GPIO 32

/* GPIO Output Logic */
#define GPIO_OUTPUT_HIGH   1U

#define GPIO_OUTPUT_LOW    0U

/* GPIO Pin Index */
#define GPIO_PIN_0         0U
#define GPIO_PIN_1         1U
#define GPIO_PIN_2         2U
#define GPIO_PIN_3         3U
#define GPIO_PIN_4         4U

#define GPIO_PIN_13        13U
#define GPIO_PIN_14        14U
#define GPIO_PIN_15        15U
#define GPIO_PIN_16        16U
#define GPIO_PIN_17        17U
#define GPIO_PIN_22        22U

enum gpio_direction {
	GPIO_INPUT,
	GPIO_OUTPUT
};

struct gpio_cfg {
	// uint32_t pin;
};

struct gpio_instance {
	const char *instance_name;
	uint32_t    base_address;
	// struct gpio_cfg gpio_config[MAX_NUMBER_OF_GPIO];
};

/**
 * gpio_pins_init() initializes local data structure used to access the GPIO
 * instance.
 */
void gpio_pins_init(struct gpio_instance *this_gpio,
					uint32_t              base_addr,
					uint32_t              lines_num,
					uint32_t              gpio_dirs);

/**
 * gpio_pin_set_dir() configures the direction of the specified GPIO pin as
 * either input or output.
 */
void gpio_pin_set_dir(struct gpio_instance *this_gpio,
					  uint32_t              pin,
					  enum gpio_direction   gpio_dir);

/**
 * gpio_pin_write() sets the output value of the specified GPIO pin to high
 * or low.
 */
void gpio_pin_write(struct gpio_instance *this_gpio,
					uint32_t              pin,
					uint32_t              value);

/**
 * gpio_pin_read() returns the input value of the specified GPIO pin.
 */
uint32_t gpio_pin_read(struct gpio_instance *this_gpio, uint32_t index);

#endif
