/*   ==================================================================

>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
------------------------------------------------------------------
Copyright (c) 2025-2025 by Lattice Semiconductor Corporation
ALL RIGHTS RESERVED
------------------------------------------------------------------

  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
  DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

  Lattice grants permission to use this code pursuant to the
  terms of the Lattice Propel License Agreement.

DISCLAIMER:

LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
WHETHER EXPRESSED, IMPLIED, STATUTORY,
OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
COMMUNICATION WITH LICENSEE,
AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
UNINTERRUPTED OR ERROR FREE,
OR THAT DEFECTS HEREIN WILL BE CORRECTED.
LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
AND RESULTS OBTAINED THEREFROM.
LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
CORRECTION,
OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
INCLUDING LOST PROFITS,
ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
IS SET FORTH ABOVE.
LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
------------------------------------------------------------------

================================================================== */
#ifndef OCTAL_SPI_CONTROLLER_H_
#define OCTAL_SPI_CONTROLLER_H_

// ----------------------------------------------
// Select SPI device
//#define _MICRON_X4_FLASH_DEVICE_
#define _WINBOND_X4_FLASH_DEVICE_
//#define _MACRONIX_X4_FLASH_DEVICE_
// ----------------------------------------------

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define OCTAL_SPI_CONTROLLER_DRV_VER "v25.1.0"

/**
 * Temporary workaround to read the flash in chunks of 256 bytes.
 */
#define FLASH_READ_CHUNK_SIZE 256U

//Success and Failure
#define FAILURE                         0
#define SUCCESS                         1

//Set And Clear
#define GET_REG_MASK(F_LEN,F_IDX)       (unsigned int)(((0x00000001 << F_LEN) - 1) << F_IDX)
#define PUT_FIELD_VAL(F_VALUE,F_LEN,\
                      F_IDX)            (unsigned int)((unsigned int)(F_VALUE << F_IDX) & GET_REG_MASK(F_LEN,F_IDX))
#define SET_REG_FIELD(REG_VAR,F_VALUE,\
                      F_LEN,F_IDX)      REG_VAR = (unsigned int)(((unsigned int)REG_VAR & ~(GET_REG_MASK(F_LEN,F_IDX))) | \
                                                                PUT_FIELD_VAL(F_VALUE,F_LEN,F_IDX))

#define CLEAR                           0x00000000
#define SET_ALL_BITS                    0xFFFFFFFF
#define ZERO                            0
#define DAT32B_SWAP_BYTES(DATA)         ((DATA >> 24) & 0xFF      ) | \
                                        ((DATA >>  8) & 0xFF00    ) | \
                                        ((DATA <<  8) & 0xFF0000  ) | \
                                        ((DATA << 24) & 0xFF000000)

#define DAT24B_SWAP_BYTES(DATA)         ((DATA >> 16) & 0xFF      ) | \
                                        ((DATA      ) & 0xFF00    ) | \
                                        ((DATA << 16) & 0xFF0000  )

#define GET8B_AND_CONCAT4X(DATA)        ((0xFF & DATA)      ) | \
                                        ((0xFF & DATA) <<  8) | \
                                        ((0xFF & DATA) << 16) | \
                                        ((0xFF & DATA) << 24)

#define GET_FIELD_VAL(DATA, F_IDX,\
                      F_LEN)            (((DATA) >> (F_IDX)) & ((1 << (F_LEN)) - 1))

#define CALC_DWORD_LEN(BYTE_LEN)        ((BYTE_LEN >> 2) + ((BYTE_LEN & 0x3)?  1 : 0))

// Register Offset
#define SPIX8_ADR_IPCORE_ID             0x000
#define SPIX8_ADR_CONFIG0               0x004
#define SPIX8_ADR_CONFIG1               0x008
#define SPIX8_ADR_SUPCMD_CODE0          0x00C
#define SPIX8_ADR_SUPCMD_CODE1          0x010
#define SPIX8_ADR_SUPCMD_CODE2          0x014
#define SPIX8_ADR_SUPCMD_CFG            0x018
#define SPIX8_ADR_MIN_TGT_SIZE          0x02C
#define SPIX8_ADR_TGT_ADDROFST          0x030
#define SPIX8_ADR_TOT_TGT_SIZE          0x034
#define SPIX8_ADR_TGT_AXI4BASE          0x038
#define SPIX8_ADR_INT_ENABLE            0x03C

#define SPIX8_ADR_INT_STATUS            0x100
#define SPIX8_ADR_GENCMD_CNTR           0x104
#define SPIX8_ADR_SUPCMD_CNTR           0x108
#define SPIX8_ADR_DEBUG_INFO0           0x10C
#define SPIX8_ADR_DEBUG_INFO1           0x110

#define SPIX8_ADR_TX_FIFO               0x200
#define SPIX8_ADR_RX_FIFO               0x204
#define SPIX8_ADR_PKT_HDR0              0x208
#define SPIX8_ADR_PKT_HDR1              0x20C
#define SPIX8_ADR_PKT_HDR2              0x210
#define SPIX8_ADR_PKT_HDR3              0x214
#define SPIX8_ADR_WRITE_DATA            0x218
#define SPIX8_ADR_READ_DATA             0x21C
#define SPIX8_ADR_START_XFER            0x220
#define SPIX8_ADR_INT_SET               0x224
#define SPIX8_ADR_TEST_MODE             0x228
#define SPIX8_ADR_SOFT_RESET            0x22C
#define SPIX8_ADR_IO_DELAY_CTL          0x230

// Soft Reset bit fields
#define IP_CORE_RST                     0x00000001
#define IP_CSR_RST                      0x00000002
#define TX_FIFO_RST                     0x00000004
#define RX_FIFO_RST                     0x00000008
#define SPI_TGT_RST                     0x00000010

#define SPIX8_INT_FLASH_PROGRAM_FAIL    0x00020000
#define SPIX8_INT_FLASH_ERASE_FAIL      0x00010000
#define SPIX8_INT_ESPI_CRC_ERROR        0x00008000
#define SPIX8_INT_RD_ON_EMTY_ERROR      0x00002000
#define SPIX8_INT_WR_ON_FULL_ERROR      0x00001000
#define SPIX8_INT_BUS_ACCESS_ERROR      0x00000800
#define SPIX8_INT_USER_PKT_DECODE_ERROR 0x00000400
#define SPIX8_INT_SUP_RD_TRANS_CNT_HIT  0x00000200
#define SPIX8_INT_SUP_WR_TRANS_CNT_HIT  0x00000100
#define SPIX8_INT_GEN_RD_TRANS_CNT_HIT  0x00000080
#define SPIX8_INT_GEN_WR_TRANS_CNT_HIT  0x00000040
#define SPIX8_INT_RDATA_AVAILABLE       0x00000020
#define SPIX8_INT_WDATA_DONE            0x00000010
#define SPIX8_INT_RXFIFO_NOT_EMTY       0x00000008
#define SPIX8_INT_RXFIFO_AFUL           0x00000004
#define SPIX8_INT_TXFIFO_EMTY           0x00000002
#define SPIX8_INT_TXFIFO_AFUL           0x00000001

#define SPIX8_CONFIG0_SCK_RATE          0x00001F00
#define SPIX8_CONFIG0_AUTO_CLR_RST      0x00100000

#define SPIX8_CFG0_LSBF_IDX             0
#define SPIX8_CFG0_CPHA_IDX             1
#define SPIX8_CFG0_CPOL_IDX             2
#define SPIX8_CFG0_SCK_RATE_IDX         8
#define SPIX8_CFG0_ENDIANNESS_IDX       16
#define SPIX8_CFG0_EN_ADDR_MAP_IDX      17
#define SPIX8_CFG0_AUTOCLR_TXSTART_IDX  19
#define SPIX8_CFG0_AUTOCLR_SOFTRST_IDX  20
#define SPIX8_CFG0_USE_DS_IDX           21
#define SPIX8_CFG0_NONBLOCK_TXFIFO_IDX  22
#define SPIX8_CFG0_NONBLOCK_RXFIFO_IDX  23

#define SPIX8_DEBUG0_SPI_BUSY           0x00000001
#define SPIX8_DEBUG0_SPI_STARTED        0x00000008

#define SUPCMD_CFG_LANE_WIDTH_IDX       0
#define SUPCMD_CFG_XFER_RATE_IDX        4
#define SUPCMD_CFG_WAIT_DS_IDX          7
#define SUPCMD_CFG_RDSR_DUMMY_IDX       8
#define SUPCMD_CFG_RDSCUR_WIDTH_IDX     16
#define SUPCMD_CFG_FASTRD_DUMMY_IDX     24
#define SUPCMD_CFG_ADDR_MODE_IDX        31

#define SUPCMD_CFG_LANE_WIDTH_WID       4
#define SUPCMD_CFG_XFER_RATE_WID        3
#define SUPCMD_CFG_WAIT_DS_WID          1
#define SUPCMD_CFG_RDSR_DUMMY_WID       5
#define SUPCMD_CFG_RDSCUR_WIDTH_WID     5
#define SUPCMD_CFG_FASTRD_DUMMY_WID     5
#define SUPCMD_CFG_ADDR_MODE_WID        1

// DW 0
#define PKTHDR_SUP_FCC_WID              1
#define PKTHDR_CMDTYPE_WID              1
#define PKTHDR_LANEWID_WID              2
#define PKTHDR_DATRATE_WID              1
#define PKTHDR_FRM_SOP_WID              1
#define PKTHDR_FRM_EOP_WID              1
#define PKTHDR_DUMMYDT_WID              1
#define PKTHDR_USEDSTB_WID              1
#define PKTHDR_G_TGTCS_WID              5
#define PKTHDR_NUM1SCK_WID              3
#define PKTHDR_XFERLEN_WID              16

#define PKTHDR_WITHDAT_WID              1
#define PKTHDR_USR_CMD_WID              5
#define PKTHDR_EN2BFCC_WID              1
#define PKTHDR_NUM8SCK_WID              8
// DW 1
#define PKTHDR_CAD_WID_WID              4
#define PKTHDR_XFRRATE_WID              3
#define PKTHDR_WAIT_DS_WID              1
#define PKTHDR_S_TGTCS_WID              5
#define PKTHDR_FADRWID_WID              3
#define PKTHDR_CMDCODE_WID              16
// DW 2
#define PKTHDR_FADDR_0_WID              32
// DW 3
#define PKTHDR_FADDR_1_WID              32

// DW 0
#define PKTHDR_SUP_FCC_IDX              0               //  1b - sup=0 sup_flash_cmd
#define PKTHDR_CMDTYPE_IDX              1               //  1b - sup=0 cmd_type
#define PKTHDR_LANEWID_IDX              2               //  2b - sup=0 lane_width[1:0]
#define PKTHDR_DATRATE_IDX              4               //  1b - sup=0 data_rate
#define PKTHDR_FRM_SOP_IDX              5               //  1b - sup=0 frm_start
#define PKTHDR_FRM_EOP_IDX              6               //  1b - sup=0 frm_end
#define PKTHDR_DUMMYDT_IDX              7               //  1b - sup=0 dummy_data
#define PKTHDR_USEDSTB_IDX              7               //  1b - sup=0 use_ddr_ds
#define PKTHDR_G_TGTCS_IDX              8               //  5b - sup=0 tgt_cs[4:0]
#define PKTHDR_NUM1SCK_IDX              13              //  3b - sup=0 num_wait_sck[2:0]
#define PKTHDR_XFERLEN_IDX              16              // 16b - sup=0 xfer_len[15:0]

#define PKTHDR_WITHDAT_IDX              1               //  1b - sup=1 with_payload
#define PKTHDR_USR_CMD_IDX              2               //  5b - sup=1 user_cmd_code[4:0]
#define PKTHDR_EN2BFCC_IDX              7               //  1b - sup=1 en_2byte_fcc
#define PKTHDR_NUM8SCK_IDX              8               //  8b - sup=1 num_wait_state[7:0]
// DW 1
#define PKTHDR_CAD_WID_IDX              0               //  4b - sup=1 lane_width[3:0]
#define PKTHDR_XFRRATE_IDX              4               //  3b - sup=1 xfer_rate[2:0]
#define PKTHDR_WAIT_DS_IDX              7               //  1b - sup=1 wait_data_strobe
#define PKTHDR_S_TGTCS_IDX              8               //  5b - sup=1 tgt_cs[4:0]
#define PKTHDR_FADRWID_IDX              13              //  3b - sup=1 flash_addr_width[2:0]
#define PKTHDR_CMDCODE_IDX              16              // 16b - sup=1 flash_command_code[15:0]
// DW 2
#define PKTHDR_FADDR_0_IDX              0               // 32b - sup=1 flash_addr[31:0]/flash_addr[63:32]
// DW 3
#define PKTHDR_FADDR_1_IDX              0               // 32b - sup=1 flash_addr[31:0]


#define PKTHDR_SUP_FCC_MASK             0x00000001
#define PKTHDR_CMDTYPE_MASK             0x00000002
#define PKTHDR_LANEWID_MASK             0x0000000C
#define PKTHDR_DATRATE_MASK             0x00000010
#define PKTHDR_FRM_SOP_MASK             0x00000020
#define PKTHDR_FRM_EOP_MASK             0x00000040
#define PKTHDR_DUMMYDT_MASK             0x00000080
#define PKTHDR_G_TGTCS_MASK             0x00001F00
#define PKTHDR_NUM1SCK_MASK             0x0000E000
#define PKTHDR_XFERLEN_MASK             0xFFFF0000

#define PKTHDR_WITHDAT_MASK             0x00000002
#define PKTHDR_USR_CMD_MASK             0x0000007C
#define PKTHDR_EN2BFCC_MASK             0x00000080
#define PKTHDR_NUM8SCK_MASK             0x0000FF00

#define PKTHDR_CAD_WID_MASK             0x0000000F
#define PKTHDR_XFRRATE_MASK             0x00000070
#define PKTHDR_WAIT_DS_MASK             0x00000080
#define PKTHDR_S_TGTCS_MASK             0x00001F00
#define PKTHDR_FADRWID_MASK             0x0000E000
#define PKTHDR_CMDCODE_MASK             0xFFFF0000

#define FLASH_CMDPATTERN_0              0             // [OPCODE], [ADDRESS] , [RD DATA]
#define FLASH_CMDPATTERN_1              1             // [OPCODE], [ADDRESS], [WR DATA]
#define FLASH_CMDPATTERN_2              2             // [WR ENABLE], [OPCODE], [ADDRESS], [WR DATA]
#define FLASH_CMDPATTERN_3              3             // [WR ENABLE], [OPCODE], [ADDRESS], [WR DATA], [CHECK STATUS]
#define USRCMD_REG_CFG_SETTING          0x00
#define USRCMD_PKT_HDR_SETTING          0x10

#define SPIX8_GEN_CMD                   0
#define SPIX8_SUP_CMD                   1
#define SPIX8_WR_CMD                    1
#define SPIX8_RD_CMD                    0

#define SPIX8_IO_X1                     0
#define SPIX8_IO_X2                     1
#define SPIX8_IO_X4                     2
#define SPIX8_IO_X8                     3

// io width: CMD/ADR/DAT
#define SPIX8_IO_X1_X1_X1               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X1 << 2) & 0x0C) | (SPIX8_IO_X1 & 0x03) )
#define SPIX8_IO_X2_X2_X2               ( ((SPIX8_IO_X2 << 4) & 0x30) | ((SPIX8_IO_X2 << 2) & 0x0C) | (SPIX8_IO_X2 & 0x03) )
#define SPIX8_IO_X4_X4_X4               ( ((SPIX8_IO_X4 << 4) & 0x30) | ((SPIX8_IO_X4 << 2) & 0x0C) | (SPIX8_IO_X4 & 0x03) )
#define SPIX8_IO_X8_X8_X8               ( ((SPIX8_IO_X8 << 4) & 0x30) | ((SPIX8_IO_X8 << 2) & 0x0C) | (SPIX8_IO_X8 & 0x03) )
#define SPIX8_IO_X1_X1_X2               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X1 << 2) & 0x0C) | (SPIX8_IO_X2 & 0x03) )
#define SPIX8_IO_X1_X2_X2               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X2 << 2) & 0x0C) | (SPIX8_IO_X2 & 0x03) )
#define SPIX8_IO_X1_X1_X4               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X1 << 2) & 0x0C) | (SPIX8_IO_X4 & 0x03) )
#define SPIX8_IO_X1_X4_X4               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X4 << 2) & 0x0C) | (SPIX8_IO_X4 & 0x03) )
#define SPIX8_IO_X1_X1_X8               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X1 << 2) & 0x0C) | (SPIX8_IO_X8 & 0x03) )
#define SPIX8_IO_X1_X8_X8               ( ((SPIX8_IO_X1 << 4) & 0x30) | ((SPIX8_IO_X8 << 2) & 0x0C) | (SPIX8_IO_X8 & 0x03) )

#define FLASH_IO_MODE_EXTSPI          0xFF
#define FLASH_IO_MODE_OCTSPI          0xE7
#define FLASH_IO_MODE_EXTSPI_NODQS    0xDF
#define FLASH_IO_MODE_OCTSPI_NODQS    0xC7

#define SPIX8_STR                       0
#define SPIX8_DTR                       1

#define SPIX8_DLYCTRL_TYPE_IDX          21
#define SPIX8_DLYCTRL_DIR_IDX           20
#define SPIX8_DLYCTRL_SEL_IDX           17
#define SPIX8_DLYCTRL_REQ_IDX           16
#define SPIX8_DLYCTRL_CFLAG_IDX         12
#define SPIX8_DLYCTRL_STEP_IDX          0

#define DLYCTRL_TYPE_LOAD               0
#define DLYCTRL_TYPE_MOVE               1
#define DLYCTRL_SEL_DQ                  1
#define DLYCTRL_SEL_DS                  2
#define DLYCTRL_SEL_CK                  4
#define DLYCTRL_DIR_INCR                0
#define DLYCTRL_DIR_DECR                1

#define FLASH_EXTSPI_ENABLE             0
#define FLASH_OCTSPI_ENABLE             1
#define FLASH_QUADSPI_ENABLE            1
#define FLASH_ADDR_MODE_24B             0
#define FLASH_ADDR_MODE_32B             1
#define FLASH_XIP_MODE_OFF              0
#define FLASH_XIP_MODE_ON               1

#ifdef _MICRON_X4_FLASH_DEVICE_
  #define FLASH_NUM_RDID_BYTES          20
  #define FLASH_NUM_RDID_DWORDS         5

  #define FLASH_PAGE_PROG               0
  #define FLASH_OCTIN_FAST_PROG         1
  #define FLASH_EXT_OCTIN_FAST_PROG     2

  #define FLASH_ERASE_4KB               0
  #define FLASH_ERASE_32KB              1
  #define FLASH_ERASE_128KB             2
  #define FLASH_ERASE_CHIP              3

  #define FLASH_READ                    0
  #define FLASH_FAST_READ               1
  #define FLASH_OCTOUT_FAST_READ        2
  #define FLASH_OCT_IO_FAST_READ        3
  #define FLASH_DDR_OCTOUT_FAST_READ    4
  #define FLASH_DDR_OCT_IO_FAST_READ    5

  #define FLASH_REG_VOLATILE            0
  #define FLASH_REG_NON_VOLATILE        1
  #define FLASH_REG_STATUS              2
  #define FLASH_REG_PROT_MGMT           3
  #define FLASH_REG_GEN_PURPOSE         4

  #define FLASH_IO_MODE_EXTSPI          0xFF
  #define FLASH_IO_MODE_OCTSPI          0xE7
  #define FLASH_IO_MODE_EXTSPI_NODQS    0xDF
  #define FLASH_IO_MODE_OCTSPI_NODQS    0xC7

  #define FLASH_DRVSTR_50               0xFF
  #define FLASH_DRVSTR_35               0xFE
  #define FLASH_DRVSTR_25               0xFD
  #define FLASH_DRVSTR_18               0xFC

  #define FLASH_WRAP_INF                0xFF
  #define FLASH_WRAP_64                 0xFE
  #define FLASH_WRAP_32                 0xFD
  #define FLASH_WRAP_16                 0xFC

  #define FLASH_ADDR_3BYTES             0xFF
  #define FLASH_ADDR_4BYTES             0xFE

  #define FLASH_XIP_DISABLED            0xFF
  #define FLASH_XIP_ENABLED             0xFE

  // Micron Flash status register bits
  #define FLASH_STS_WIP_IDX             0
  #define FLASH_STS_WEN_IDX             1
  #define FLASH_STS_BP_L_IDX            2
  #define FLASH_STS_BP_H_IDX            6
  #define FLASH_STS_TOP_BOT_IDX         5
  #define FLASH_STS_REGWREN_IDX         7

  // Micron Flash status flag register bits
  #define FLASH_FLG_ADDRESSING_IDX      0
  #define FLASH_FLG_PROTECTION_IDX      1
  #define FLASH_FLG_PROGM_SUSP_IDX      2
  #define FLASH_FLG_PROGM_FAIL_IDX      4
  #define FLASH_FLG_ERASE_FAIL_IDX      5
  #define FLASH_FLG_ERASE_SUSP_IDX      6
  #define FLASH_FLG_PRGM_ERASE_IDX      7

  // Micron Flash command codes
  #define FLASH_CMD_ENQPI               0x35353535
  #define FLASH_CMD_EXQPI               0xF5F5F5F5
  #define FLASH_CMD_RDNVCR              0xB5B5B5B5
  #define FLASH_CMD_RDVCR               0x85858585
  #define FLASH_CMD_WRNVCR              0xB1B1B1B1
  #define FLASH_CMD_WRVCR               0x81818181
  #define FLASH_CMD_RDSR                0x05050505
  #define FLASH_CMD_WRSR                0x01010101
  #define FLASH_CMD_WREN                0x06060606
  #define FLASH_CMD_WRDI                0x04040404
  #define FLASH_CMD_RDFSR               0x70707070
  #define FLASH_CMD_CLRFSR              0x50505050
  #define FLASH_CMD_EN4BYTE             0xB7B7B7B7
  #define FLASH_CMD_EX4BYTE             0xE9E9E9E9
  #define FLASH_CMD_READ                0x03030303
  #define FLASH_CMD_FAST_READ           0x0B0B0B0B
  #define FLASH_CMD_8OFR                0x8B8B8B8B
  #define FLASH_CMD_8IOFR               0xCBCBCBCB
  #define FLASH_CMD_8OFRDTR             0x9D9D9D9D
  #define FLASH_CMD_8IOFRDTR            0xFDFDFDFD
  #define FLASH_CMD_READ4BYTE           0x13131313
  #define FLASH_CMD_4IOFR4BYTE          0xEBEBEBEB
  #define FLASH_CMD_FAST_READ4BYTE      0x0C0C0C0C
  #define FLASH_CMD_8OFR4BYTE           0x7C7C7C7C
  #define FLASH_CMD_8IOFR4BYTE          0xCCCCCCCC
  #define FLASH_CMD_RSTEN               0x66666666
  #define FLASH_CMD_RSTMEM              0x99999999
  #define FLASH_CMD_RDSFDP              0x5A5A5A5A
  #define FLASH_CMD_RDID                0x9E9E9E9E
  #define FLASH_CMD_RDID1               0x9F9F9F9F
  #define FLASH_CMD_RDGPRR              0x96969696
  #define FLASH_CMD_ROTP                0x4B4B4B4B
  #define FLASH_CMD_POTP                0x42424242
  #define FLASH_CMD_RDPMR               0x2B2B2B2B
  #define FLASH_CMD_PPMR                0x68686868
  #define FLASH_CMD_DYBRD               0xE8E8E8E8
  #define FLASH_CMD_DYBRD4BYTE          0xE0E0E0E0
  #define FLASH_CMD_DYBWR               0xE5E5E5E5
  #define FLASH_CMD_DYBWR4BYTE          0xE1E1E1E1
  #define FLASH_CMD_PPBRD               0xE2E2E2E2
  #define FLASH_CMD_PPBP                0xE3E3E3E3
  #define FLASH_CMD_PPBE                0xE4E4E4E4
  #define FLASH_CMD_PLBRD               0xA7A7A7A7
  #define FLASH_CMD_PLBWR               0xA6A6A6A6
  #define FLASH_CMD_ASPRD               0x2D2D2D2D
  #define FLASH_CMD_ASPP                0x2C2C2C2C
  #define FLASH_CMD_PASSRD              0x27272727
  #define FLASH_CMD_PASSP               0x28282828
  #define FLASH_CMD_PASSU               0x29292929
  #define FLASH_CMD_PES                 0x75757575
  #define FLASH_CMD_PER                 0x7A7A7A7A
  #define FLASH_CMD_PP                  0x02020202
  #define FLASH_CMD_PP4BYTE             0x12121212
  #define FLASH_CMD_8IFP                0x82828282
  #define FLASH_CMD_8IFP4BYTE           0x84848484
  #define FLASH_CMD_8IEFP               0xC2C2C2C2
  #define FLASH_CMD_8IEFP4BYTE          0x8E8E8E8E
  #define FLASH_CMD_SE                  0xD8D8D8D8
  #define FLASH_CMD_SE4BYTE             0xDCDCDCDC
  #define FLASH_CMD_DPD                 0xB9B9B9B9
  #define FLASH_CMD_RDPD                0xABABABAB
  #define FLASH_CMD_BE                  0xC7C7C7C7
  #define FLASH_CMD_BE2                 0x60606060
  #define FLASH_CMD_SSE                 0x20202020
  #define FLASH_CMD_SSE4BYTE            0x21212121
  #define FLASH_CMD_SSE32K              0x52525252
  #define FLASH_CMD_SSE32K4BYTE         0x5C5C5C5C
  #define FLASH_CMD_EFI                 0x9B9B9B9B
  #define FLASH_CMD_MSE                 0x26262626
  #define FLASH_CMD_DIEER               0xC4C4C4C4
  #define FLASH_CMD_TDP                 0x48484848
#endif /*_MICRON_X4_FLASH_DEVICE_*/

#ifdef _WINBOND_X4_FLASH_DEVICE_
  #define FLASH_NUM_RDID_BYTES          4
  #define FLASH_NUM_RDID_DWORDS         1

  #define FLASH_PAGE_PROG               0
  #define FLASH_QUAD_FAST_PROG          1
  #define FLASH_EXT_QUAD_FAST_PROG      2

  #define FLASH_ERASE_4KB               0
  #define FLASH_ERASE_32KB              1
  #define FLASH_ERASE_64KB              2
  #define FLASH_ERASE_CHIP              3

  #define FLASH_READ                    0
  #define FLASH_FAST_READ               1
  #define FLASH_FAST_READ_2DO           2
  #define FLASH_FAST_READ_2IO           3
  #define FLASH_FAST_READ_4DO           4
  #define FLASH_FAST_READ_4IO           5
  #define FLASH_FAST_READ_1IODTR        6
  #define FLASH_FAST_READ_2IODTR        7
  #define FLASH_FAST_READ_4IODTR        8

  #define FLASH_REG_VOLATILE            0
  #define FLASH_REG_NON_VOLATILE        1
  #define FLASH_REG_STATUS              2

  // Winbond Flash status register bits
  #define FLASH_STS_WIP_IDX             0
  #define FLASH_STS_WEN_IDX             1
  #define FLASH_STS_BP_L_IDX            2
  #define FLASH_STS_BP_H_IDX            5
  #define FLASH_STS_TOP_BOT_IDX         6
  #define FLASH_STS_REGPROT_IDX         7

  // Winbond Flash command codes
  #define FLASH_CMD_RSTEN               0x66666666
  #define FLASH_CMD_RSTMEM              0x99999999
  #define FLASH_CMD_EN4BYTE             0xB7B7B7B7
  #define FLASH_CMD_EX4BYTE             0xE9E9E9E9
  #define FLASH_CMD_ENQPI               0x38383838
  #define FLASH_CMD_EXQPI               0xFFFFFFFF
  #define FLASH_CMD_SETBURSTWRAP        0x77777777
  #define FLASH_CMD_SETREADPARAM        0xC0C0C0C0

  #define FLASH_CMD_WREN                0x06060606
  #define FLASH_CMD_WREN_VSR            0x50505050
  #define FLASH_CMD_WRDI                0x04040404
  #define FLASH_CMD_RDID                0xABABABAB
  #define FLASH_CMD_RDMFGID             0x90909090
  #define FLASH_CMD_RDJDCID             0x9F9F9F9F
  #define FLASH_CMD_RDUNQID             0x4B4B4B4B
  #define FLASH_CMD_RDSR                0x05050505
  #define FLASH_CMD_RDSR2               0x35353535
  #define FLASH_CMD_RDSR3               0x15151515
  #define FLASH_CMD_WRSR                0x01010101
  #define FLASH_CMD_WRSR2               0x31313131
  #define FLASH_CMD_WRSR3               0x11111111

  #define FLASH_CMD_BE                  0xC7C7C7C7
  #define FLASH_CMD_BE2                 0x60606060
  #define FLASH_CMD_SE                  0xD8D8D8D8
  #define FLASH_CMD_SSE32K              0x52525252
  #define FLASH_CMD_SSE                 0x20202020
  #define FLASH_CMD_SE4BYTE             0xDCDCDCDC
  #define FLASH_CMD_SSE32K4BYTE         0x52525252
  #define FLASH_CMD_SSE4BYTE            0x21212121

  #define FLASH_CMD_PP                  0x02020202
  #define FLASH_CMD_PP4BYTE             0x12121212
  #define FLASH_CMD_4IPP                0x32323232
  #define FLASH_CMD_4IPP4BYTE           0x34343434

  #define FLASH_CMD_READ                0x03030303 // 1-1-1
  #define FLASH_CMD_FAST_READ           0x0B0B0B0B // 1-1-1, 4-4-4
  #define FLASH_CMD_2OFR                0x3B3B3B3B // 1-1-2
  #define FLASH_CMD_2IOFR               0xBBBBBBBB // 1-2-2, XiP
  #define FLASH_CMD_4OFR                0x6B6B6B6B // 1-1-4
  #define FLASH_CMD_4IOFR               0xEBEBEBEB // 1-4-4, 4-4-4, XiP
                                                  //
  #define FLASH_CMD_READ4BYTE           0x13131313 // 1-1-1
  #define FLASH_CMD_FAST_READ4BYTE      0x0C0C0C0C // 1-1-1
  #define FLASH_CMD_2OFR4BYTE           0x3C3C3C3C // 1-1-2
  #define FLASH_CMD_2IOFR4BYTE          0xBCBCBCBC // 1-2-2, XiP
  #define FLASH_CMD_4OFR4BYTE           0x6C6C6C6C // 1-1-4
  #define FLASH_CMD_4IOFR4BYTE          0xECECECEC // 1-4-4, XiP
                                                  //
  #define FLASH_CMD_FAST_READ_DTR       0x0D0D0D0D // 1-1-1, 4-4-4
  #define FLASH_CMD_2IOFR_DTR           0xBDBDBDBD // 1-2-2, XiP
  #define FLASH_CMD_4IOFR_DTR           0xEDEDEDED // 1-4-4, 4-4-4, XiP
#endif /*_WINBOND_X4_FLASH_DEVICE_*/

#ifdef _MACRONIX_X4_FLASH_DEVICE_
  #define FLASH_NUM_RDID_BYTES          4
  #define FLASH_NUM_RDID_DWORDS         1

  #define FLASH_PAGE_PROG               0
  #define FLASH_QUAD_FAST_PROG          1
  #define FLASH_EXT_QUAD_FAST_PROG      2

  #define FLASH_ERASE_4KB               0
  #define FLASH_ERASE_32KB              1
  #define FLASH_ERASE_64KB              2
  #define FLASH_ERASE_CHIP              3

  #define FLASH_READ                    0
  #define FLASH_FAST_READ               1
  #define FLASH_FAST_READ_2DO           2
  #define FLASH_FAST_READ_2IO           3
  #define FLASH_FAST_READ_4DO           4
  #define FLASH_FAST_READ_4IO           5
  #define FLASH_FAST_READ_1IODTR        6
  #define FLASH_FAST_READ_2IODTR        7
  #define FLASH_FAST_READ_4IODTR        8

  #define FLASH_REG_VOLATILE            0
  #define FLASH_REG_NON_VOLATILE        1
  #define FLASH_REG_STATUS              2

  // Macronix Flash status register bits
  #define FLASH_STS_WIP_IDX             0
  #define FLASH_STS_WEN_IDX             1
  #define FLASH_STS_BP_L_IDX            2
  #define FLASH_STS_BP_H_IDX            5
  #define FLASH_STS_TOP_BOT_IDX         6
  #define FLASH_STS_REGPROT_IDX         7

  // Macronix Flash command codes
  #define FLASH_CMD_RSTEN               0x66666666
  #define FLASH_CMD_RSTMEM              0x99999999
  #define FLASH_CMD_EN4BYTE             0xB7B7B7B7
  #define FLASH_CMD_EX4BYTE             0xE9E9E9E9
  #define FLASH_CMD_ENQPI               0x35353535
  #define FLASH_CMD_EXQPI               0xFFFFFFFF
  #define FLASH_CMD_SETBURSTWRAP        0x77777777
  #define FLASH_CMD_SETREADPARAM        0xC0C0C0C0

  #define FLASH_CMD_WREN                0x06060606
  #define FLASH_CMD_WREN_VSR            0x50505050
  #define FLASH_CMD_WRDI                0x04040404
  #define FLASH_CMD_RDID                0xABABABAB
  #define FLASH_CMD_RDMFGID             0x90909090
  #define FLASH_CMD_RDJDCID             0x9F9F9F9F
  #define FLASH_CMD_RDUNQID             0x4B4B4B4B
  #define FLASH_CMD_RDSR                0x05050505
  #define FLASH_CMD_RDSR2               0x35353535
  #define FLASH_CMD_RDSR3               0x15151515
  #define FLASH_CMD_WRSR                0x01010101
  #define FLASH_CMD_WRSR2               0x31313131
  #define FLASH_CMD_WRSR3               0x11111111

  #define FLASH_CMD_BE                  0xC7C7C7C7
  #define FLASH_CMD_BE2                 0x60606060
  #define FLASH_CMD_SE                  0xD8D8D8D8
  #define FLASH_CMD_SSE32K              0x52525252
  #define FLASH_CMD_SSE                 0x20202020
  #define FLASH_CMD_SE4BYTE             0xDCDCDCDC
  #define FLASH_CMD_SSE32K4BYTE         0x52525252
  #define FLASH_CMD_SSE4BYTE            0x21212121

  #define FLASH_CMD_PP                  0x02020202
  #define FLASH_CMD_PP4BYTE             0x12121212
  #define FLASH_CMD_4IPP                0x32323232
  #define FLASH_CMD_4IPP4BYTE           0x34343434

  #define FLASH_CMD_READ                0x03030303 // 1-1-1
  #define FLASH_CMD_FAST_READ           0x0B0B0B0B // 1-1-1, 4-4-4
  #define FLASH_CMD_2OFR                0x3B3B3B3B // 1-1-2
  #define FLASH_CMD_2IOFR               0xBBBBBBBB // 1-2-2, XiP
  #define FLASH_CMD_4OFR                0x6B6B6B6B // 1-1-4
  #define FLASH_CMD_4IOFR               0xEBEBEBEB // 1-4-4, 4-4-4, XiP
                                                  //
  #define FLASH_CMD_READ4BYTE           0x13131313 // 1-1-1
  #define FLASH_CMD_FAST_READ4BYTE      0x0C0C0C0C // 1-1-1
  #define FLASH_CMD_2OFR4BYTE           0x3C3C3C3C // 1-1-2
  #define FLASH_CMD_2IOFR4BYTE          0xBCBCBCBC // 1-2-2, XiP
  #define FLASH_CMD_4OFR4BYTE           0x6C6C6C6C // 1-1-4
  #define FLASH_CMD_4IOFR4BYTE          0xECECECEC // 1-4-4, XiP
                                                  //
  #define FLASH_CMD_FAST_READ_DTR       0x0D0D0D0D // 1-1-1, 4-4-4
  #define FLASH_CMD_2IOFR_DTR           0xBDBDBDBD // 1-2-2, XiP
  #define FLASH_CMD_4IOFR_DTR           0xEDEDEDED // 1-4-4, 4-4-4, XiP
#endif /*_MACRONIX_X4_FLASH_DEVICE_*/

typedef struct {
  uint8_t dat_0;
  uint8_t dat_1;
  uint8_t dat_2;
  uint8_t dat_3;
} data_4bytes_t;

typedef struct {
  uint8_t dat_0;
  uint8_t dat_1;
} data_2bytes_t;

typedef struct {
  unsigned int command;
  unsigned int cmd_width;
  unsigned int data_width;
  unsigned int adr_width;
  unsigned int cmd_io_rate;
  unsigned int data_io_rate;
  unsigned int adr_io_rate;
  unsigned int dummy_cycle;
} octal_spi_op;

typedef struct {
  unsigned int command;      /**< The command to be sent to the SPI device. */
  unsigned int cmd_width;    /**< The width of the command phase (in bits). */
  unsigned int data_width;   /**< The width of the data phase (in bits). */
  unsigned int adr_width;    /**< The width of the address phase (in bits). */
  unsigned int cmd_io_rate;  /**< The IO rate for the command phase. */
  unsigned int data_io_rate; /**< The IO rate for the data phase. */
  unsigned int adr_io_rate;  /**< The IO rate for the address phase. */
  unsigned int dummy_cycle;  /**< The number of dummy cycles to be inserted. */
} op_param_t;

typedef struct {
  volatile unsigned int SPIX8_REG_IPCORE_ID   ;
  volatile unsigned int SPIX8_REG_CONFIG0     ;
  volatile unsigned int SPIX8_REG_CONFIG1     ;
  volatile unsigned int SPIX8_REG_SUPCMD_CODE0;
  volatile unsigned int SPIX8_REG_SUPCMD_CODE1;
  volatile unsigned int SPIX8_REG_SUPCMD_CODE2;
  volatile unsigned int SPIX8_REG_SUPCMD_CFG  ;
  volatile unsigned int reserved_00[4]        ;
  volatile unsigned int SPIX8_REG_MIN_TGT_SIZE;
  volatile unsigned int SPIX8_REG_TGT_ADDROFST;
  volatile unsigned int SPIX8_REG_TOT_TGT_SIZE;
  volatile unsigned int SPIX8_REG_TGT_AXI4BASE;
  volatile unsigned int SPIX8_REG_INT_ENABLE  ;
  volatile unsigned int reserved_01[48]       ;

  volatile unsigned int SPIX8_REG_INT_STATUS  ;
  volatile unsigned int SPIX8_REG_GENCMD_CNTR ;
  volatile unsigned int SPIX8_REG_SUPCMD_CNTR ;
  volatile unsigned int SPIX8_REG_DEBUG_INFO0 ;
  volatile unsigned int SPIX8_REG_DEBUG_INFO1 ;
  volatile unsigned int reserved_02[59]       ;

  volatile unsigned int SPIX8_REG_TX_FIFO     ;
  volatile unsigned int SPIX8_REG_RX_FIFO     ;
  volatile unsigned int SPIX8_REG_PKT_HDR0    ;
  volatile unsigned int SPIX8_REG_PKT_HDR1    ;
  volatile unsigned int SPIX8_REG_PKT_HDR2    ;
  volatile unsigned int SPIX8_REG_PKT_HDR3    ;
  volatile unsigned int SPIX8_REG_WRITE_DATA  ;
  volatile unsigned int SPIX8_REG_READ_DATA   ;
  volatile unsigned int SPIX8_REG_START_XFER  ;
  volatile unsigned int SPIX8_REG_INT_SET     ;
  volatile unsigned int SPIX8_REG_TEST_MODE   ;
  volatile unsigned int SPIX8_REG_SOFT_RESET  ;
  volatile unsigned int SPIX8_REG_IO_DELAY_CTL;
} spix8_ctl_reg_t;

typedef struct {
  unsigned int init_done;
  unsigned int base_addr;
  unsigned int sck_rate;
  unsigned int autoclr_txstart;
  unsigned int autoclr_softrst;
  unsigned int spi_io_width;      /*0 - x1, 1 - x2, 2 - x4, 3 - x8*/
  unsigned int max_num_lane;
  unsigned int sys_clk_freq;
  unsigned int spi_actual_freq;
  unsigned int interrupt_enable;
  unsigned int spi_mode;    /*{cpol,cpha}*/
  unsigned int lsb_first;
  unsigned int endianness;
  unsigned int en_tgtaddr_map;
  unsigned int use_ds_in_ddr;
  unsigned int non_block_txfifo;
  unsigned int non_block_rxfifo;
  unsigned int spi_dat_rate;      /*0 - STR, 1 - DTR*/
  unsigned int min_tgtaddr_size;
  unsigned int tot_tgtaddr_size;
  unsigned int axi4_tgt_baddr;
  unsigned int flash_addr_offset;
  unsigned int flash_quad_en;
  unsigned int flash_addr_mode;
  unsigned int flash_xip_mode;
  unsigned int flash_dummy_cycle;
  unsigned int flash_wrap_cfg;

} spix8_ctl_handle_t ;

/* Externs */
extern spix8_ctl_handle_t octal_spi_c0;
extern spix8_ctl_handle_t *octal_spi_c0_inst;
extern const uint32_t flash_addr_offset;

/* Function headers*/
unsigned char spix8_flash_ctl_init(spix8_ctl_handle_t *handle,unsigned int base_addr, unsigned int flash_addr_offset);
unsigned char spix8_txfifo_wr(spix8_ctl_handle_t *handle, unsigned int *wdat, unsigned int num_dat);
unsigned char spix8_rxfifo_rd(spix8_ctl_handle_t *handle, unsigned int *rdat, unsigned int num_dat);
unsigned char wait_spi_ctl_busy_status(spix8_ctl_handle_t *handle, unsigned int wait_value, unsigned int expect_started);
unsigned char set_spi_clock_freq(spix8_ctl_handle_t *handle, unsigned int sck_freq);
unsigned char config_supported_flash_cmd(spix8_ctl_handle_t *handle, unsigned int prog_type, unsigned int read_type, unsigned int xip);
unsigned char set_quad_flash_command_config(spix8_ctl_handle_t *handle, unsigned int prog_type, unsigned int read_type, unsigned int wr1_rd0, unsigned char xip);
unsigned char gencmd_flash_soft_reset(spix8_ctl_handle_t *handle);
unsigned char gencmd_flash_set_4byte_mode(spix8_ctl_handle_t *handle, unsigned int adr_mode);
unsigned char gencmd_flash_set_quad_mode(spix8_ctl_handle_t *handle, unsigned int en_quad);
unsigned char gencmd_flash_set_read_param(spix8_ctl_handle_t *handle, unsigned int dummy_wrap_cfg);
unsigned char gencmd_flash_rdsr(spix8_ctl_handle_t *handle, unsigned int *rdat);
unsigned char gencmd_flash_rdsr123(spix8_ctl_handle_t *handle, unsigned int *rdat, unsigned int sr_type);
unsigned char gencmd_flash_rdfsr(spix8_ctl_handle_t *handle, unsigned int *rdat);
unsigned char gencmd_flash_rdid(spix8_ctl_handle_t *handle, unsigned int *rdat);
unsigned char gencmd_flash_wrsr123(spix8_ctl_handle_t *handle, unsigned int reg_data, unsigned int sr_type, unsigned int reg_type);
unsigned char flash_wr_reg(spix8_ctl_handle_t *handle, unsigned int reg_data, unsigned int reg_addr, unsigned int pkt_fmt, unsigned int reg_type);
unsigned char flash_rd_reg(spix8_ctl_handle_t *handle, unsigned int *reg_data, unsigned int reg_addr, unsigned int pkt_fmt, unsigned int reg_type, unsigned int use_data_stb);
unsigned char flash_erase(spix8_ctl_handle_t *handle, unsigned int reg_addr, unsigned int pkt_fmt, unsigned int erase_type);
unsigned char flash_program(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr, unsigned int pkt_fmt);
unsigned char flash_read(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr, unsigned int pkt_fmt, unsigned int use_data_stb);
unsigned char quad_xip_activate(spix8_ctl_handle_t *handle, unsigned int read_type);
unsigned char gencmd_octspi_erase(spix8_ctl_handle_t *handle, unsigned char erase_type, unsigned int start_addr);
unsigned char gencmd_quadspi_page_program(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr);
unsigned char gencmd_octspi_page_program(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr);
unsigned char gencmd_quadspi_fast_read(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr);
unsigned char gencmd_octspi_fast_read(spix8_ctl_handle_t *handle, unsigned int num_bytes, unsigned int *dat_buf, unsigned int start_addr);

void set_op_param(const op_param_t *params);

#endif /* OCTAL_SPI_CONTROLLER_H_ */
