/*   ==================================================================

	 >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
	 ------------------------------------------------------------------
	 Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
	 ALL RIGHTS RESERVED
	 ------------------------------------------------------------------

	   IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
	   DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

	   Lattice grants permission to use this code pursuant to the
	   terms of the Lattice Propel License Agreement.

	 DISCLAIMER:

	LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
	WHETHER EXPRESSED, IMPLIED, STATUTORY,
	OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
	COMMUNICATION WITH LICENSEE,
	AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
	MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
	LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
	LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
	SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
	UNINTERRUPTED OR ERROR FREE,
	OR THAT DEFECTS HEREIN WILL BE CORRECTED.
	LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
	ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
	AND RESULTS OBTAINED THEREFROM.
	LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
	DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
	LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
	CORRECTION,
	OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
	SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
	INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
	INCLUDING LOST PROFITS,
	ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
	EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
	LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
	IS SET FORTH ABOVE.
	LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
	ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
	INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
	RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
	FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
	 ------------------------------------------------------------------

	 ================================================================== */

#ifndef UART_H_
#define UART_H_

#include "types.h"

#define _UART_NO_INTERRUPTS_

/* LINE STATUS REGISTER BITS USED IN THE CODE */
#define UART_LSR_RX_RDY_MASK   (0x01)
#define UART_LSR_PE_MASK       (0x04)
#define UART_LSR_FE_MASK       (0x08)
#define UART_LSR_TX_RDY_MASK   (0x20)
#define UART_LSR_TX_FIFO_EMPTY (0x40)

/* INTERRUPT ENABLE REGISTER BITS USED IN THE CODE */
#define UART_IER_RX_INT_MASK   (0x01)
#define UART_IER_TX_INT_MASK   (0x02)

/* INTERRUPT IDENTIFICATION REGISTER BITS USED IN THE CODE */
#define UART_IIR_RXRDY         (0x04)
#define UART_IIR_TXRDY         (0x02)

#define UART_BUFFER_SIZE       16

struct uart_instance {
	const char *name;
	uint32_t    base;
	uint32_t    sys_clk;
	uint8_t     intrLevel;
	uint8_t     intrAvail;
	uint32_t    baudrate;
	uint32_t    databits;
	uint32_t    stopbits;
	uint8_t     rxBufferSize;
	uint8_t     txBufferSize;
	uint8_t     blockingTx;
	uint8_t     blockingRx;
	uint32_t    fifoenable;
	uint8_t     rxBuffer[UART_BUFFER_SIZE];
	uint8_t     txBuffer[UART_BUFFER_SIZE];
	uint8_t     rxWriteLoc;
	uint8_t     rxReadLoc;
	uint8_t     txWriteLoc;
	uint8_t     txReadLoc;
	uint32_t    timeoutMicroSecs;
	uint8_t     txDataBytes;
	uint8_t     rxDataBytes;
	uint32_t    errors;
	uint8_t     ier;
};

#define UART_ERR_WOULD_BLOCK      (1)
#define UART_ERR_DEVICE_ERROR     (2)
#define UART_ERR_INVALID_ARGUMENT (3)

uint8_t  uart_init(struct uart_instance *this_uart,
				   uint32_t              base_addr,
				   uint32_t              sys_clk,
				   uint32_t              baud_rate,
				   uint8_t               stop_bits,
				   uint8_t               data_width);
uint8_t  uart_putc(struct uart_instance *this_uart, uint8_t ucChar);
uint8_t  uart_getc(struct uart_instance *this_uart, uint8_t *pucChar);
uint8_t  uart_set_rate(struct uart_instance *this_uart, uint32_t baudrate);
uint8_t  uart_config(struct uart_instance *this_uart,
					 uint32_t              dwidth,
					 uint8_t               parity_en,
					 uint8_t               even_odd,
					 uint32_t              stopbits);
uint32_t uart_getchars(void *handle, uint8_t *buffer, uint32_t count);
uint32_t uart_putchars(void *handle, uint8_t *buffer, uint32_t count);

#endif /* UART_H_ */
