#-----------------------------------------------------------------------------
# Copyright (c) 2025 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# HUB  directories
#-----------------------------------------------------------------------------
# HUB app src dir
HUB_APP_DIR=$(HUB_DIR)/hub_apps
# HUB lib src dir
HUB_LIB_DIR=$(HUB_DIR)/hub_lib
# HUB include dir
HUB_INC_DIR=$(HUB_DIR)/hub_include
# HUB PY dir
HUB_PY_DIR=$(HUB_DIR)/hub_py
# HUB TEST dir (currently only for Python)
HUB_TESTS_DIR=$(HUB_DIR)/tests
# HUB examples dir
HUB_EXAMPLES_DIR=$(HUB_DIR)/examples
# HUB drivers dir
HUB_DRIVERS_DIR=$(HUB_DIR)/hub_drivers

#-----------------------------------------------------------------------------
# Controlling HUB debug prints
# Enable for detailed debug prints
#-----------------------------------------------------------------------------
# DEFINES += HUB_DEBUG

##
## HUB external dependencies
##
# HUB externals dir
HUB_EXTERNAL_DIR=$(HUB_DIR)/external
# HUB external INSTALLS dir - directory for installing HUB's dependencies
# removable via a "make dist_clean"
HUB_EXT_INSTALLS_DIR=$(OUTPUT_DIR)/hub_ext

##
## HUB packaging
##
# HUB package dir
HUB_PKG_DIR=$(OUTPUT_DIR)/package
# HUB package name as per dpkg / apt
HUB_DEB_PKG_NAME=lscc-hub

#----------------------------------------------------------------------------
# Name of the HUB library .so file
#----------------------------------------------------------------------------
HUB_LIB_NAME:=libhub.so

#-----------------------------------------------------------------------------
# pkg-config search path for HUB dependency .so
# 
# This path only applies to HUB development.
#-----------------------------------------------------------------------------
PKG_CONFIG_PATH=$(HUB_EXT_INSTALLS_DIR)/lib/pkgconfig

#-----------------------------------------------------------------------------
# TBD-DPN: Right now, only RPi ARM64 is supported
# $(shell uname -m) gives aarch64 but .deb needs arm64
#
# Chip architecture
#-----------------------------------------------------------------------------
ARCH:=arm64

#-----------------------------------------------------------------------------
# Toolchain and utils
#-----------------------------------------------------------------------------
CC=gcc
LD=ld
OCPY=objcopy
ODUMP=objdump
STRIP=strip
SZ=size

#-----------------------------------------------------------------------------
# Utility macros
#-----------------------------------------------------------------------------
ELF_TO_BIN=$(OCPY) -O binary
STRIP_ELF=$(STRIP) --strip-all
EXTRACT_DEBUG=$(OCPY) --only-keep-debug
ADD_GNU_DEBUG_LINK=$(OCPY) --add-gnu-debuglink

#-----------------------------------------------------------------------------
# toolchain flags
#-----------------------------------------------------------------------------
PRE_PROCESS_ONLY=-E -P -x c
C_OPTS = 					\
	-Wall 					\
	-Werror 				\
	-Winline				\
	-Werror=format-security	\
	-ffunction-sections 	\
	-fdata-sections     	\
    -fPIC

LDFLAGS =

export
