#-----------------------------------------------------------------------------
# Copyright (c) 2025 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------


BSP_DIR:= $(GARD_DIR)/bsp
UART_BSP_DIR:= $(BSP_DIR)/uart
I2C_BSP_DIR:= $(BSP_DIR)/i2c
I2CM_BSP_DIR:= $(BSP_DIR)/i2c_master
GPIO_BSP_DIR:= $(BSP_DIR)/gpio
OSPI_BSP_DIR:= $(BSP_DIR)/o_spi
COMMON_DIR:= $(GARD_DIR)/common
INC_DIR:= $(GARD_DIR)/inc
INTERFACE_DIR:= $(PROJECT_BASE_DIR)/src/interface
GARD_FW_DIR:= $(GARD_DIR)/fw
GARD_FW_LDR_DIR:= $(GARD_DIR)/fw_ldr
OUTPUT_DIR:= $(BUILD_DIR)/output

GARD_OUT_DIR:= $(OUTPUT_DIR)/gard_firmware
GARD_FW_OUT_DIR:= $(GARD_OUT_DIR)/fw
GARD_FW_LDR_OUT_DIR:= $(GARD_OUT_DIR)/fw_ldr


#-----------------------------------------------------------------------------
# Host platform basic utilities
#-----------------------------------------------------------------------------
MKDIR=mkdir -p
RM=rm -rf
CD=cd
FIND_IN=find

#-----------------------------------------------------------------------------
# Toolchain and utils
#-----------------------------------------------------------------------------
CC=riscv-none-embed-gcc
LD=riscv-none-embed-ld
OCPY=riscv-none-embed-objcopy
ODUMP=riscv-none-embed-objdump
STRIP=riscv-none-embed-strip
SZ=riscv-none-embed-size
LINT_TOOL=clang-tidy-18

#-----------------------------------------------------------------------------
# Utility macros
#-----------------------------------------------------------------------------
ELF_TO_BIN=$(OCPY) -O binary --gap-fill 0
STRIP_ELF=$(STRIP) --strip-all
EXTRACT_DEBUG=$(OCPY) --only-keep-debug
ADD_GNU_DEBUG_LINK=$(OCPY) --add-gnu-debuglink
GEN_DIS=$(ODUMP) -D -S
# MACRO BIN_TO_MEM needs $@ pointing to Mem file and $< pointing to Bin file
BIN_TO_MEM=srec_cat $< -Binary -fill 0x00 0x0 "$$PADDED_FILE_SIZE" -byte-swap 4 -DISable Header -Output $@ -MEM 32

#-----------------------------------------------------------------------------
# toolchain flags
#-----------------------------------------------------------------------------
PRE_PROCESS_ONLY=-E -P -x c

C_OPTS = 						\
	-march=rv32imac				\
	-mabi=ilp32 				\
	-msmall-data-limit=8		\
	-mno-save-restore			\
	-fmessage-length=0			\
	-fsigned-char				\
	-fmacro-prefix-map=$(PROJECT_BASE_DIR)=. \
	-std=gnu11					\
	--specs=picolibc.specs		\
	-nostartupfiles				\
	-nodefaultlibs				\
	-nolibc						\
	-nostdlib					\
	-Wall 						\
	-Werror 					\
	-Wno-maybe-uninitialized	\
	-Winline					\
	-fdiagnostics-color=always

ifeq ($(BUILD_TYPE),release)
C_OPTS +=						\
	-Os							\
	-Wl,--gc-sections
else
C_OPTS += -O0
endif

DEBUG_OPTS = 					\
	-g -ggdb3

LDFLAGS =						\
	-T $(OUTPUT_LD_FILE)		\
	-nostartfiles			\
	-Map "$(TGT_OUTPUT_DIR)/$(TGT_NAME).map"

# If loading firmware in multiple stages is to be supported then set this Define

#DEFINES += SUPPORT_PARTIAL_FW_LOAD

export
