/*   ==================================================================

	 >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
	 ------------------------------------------------------------------
	 Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
	 ALL RIGHTS RESERVED
	 ------------------------------------------------------------------

	   IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
	   DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

	   Lattice grants permission to use this code pursuant to the
	   terms of the Lattice Propel License Agreement.

	 DISCLAIMER:

	LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
	WHETHER EXPRESSED, IMPLIED, STATUTORY,
	OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
	COMMUNICATION WITH LICENSEE,
	AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
	MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
	LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
	LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
	SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
	UNINTERRUPTED OR ERROR FREE,
	OR THAT DEFECTS HEREIN WILL BE CORRECTED.
	LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
	ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
	AND RESULTS OBTAINED THEREFROM.
	LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
	DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
	LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
	CORRECTION,
	OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
	SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
	INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
	INCLUDING LOST PROFITS,
	ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
	EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
	LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
	IS SET FORTH ABOVE.
	LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
	ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
	INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
	RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
	FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
	 ------------------------------------------------------------------

	 ================================================================== */

#ifndef SYS_PLATFORM_H
#define SYS_PLATFORM_H

/* cpu mode setting */
#define INST_C_EXT
#define INST_M_EXT
#define INST_A_EXT

#include <riscv_errors.h>
/* general info */
#define DEVICE_FAMILY                     "LFCPNX"

/* ip instance base address */

#define RISCV_RX0_INST_NAME               "riscv_rx0_inst"
#define RISCV_RX0_INST_CLINT_BASE_ADDR    0xf2000000
#define RISCV_RX0_INST_PLIC_BASE_ADDR     0xfc000000

#define GPIO0_INST_GPIO_MEM_MAP_NAME      "gpio0_inst_gpio_mem_map"
#define GPIO0_INST_GPIO_MEM_MAP_BASE_ADDR 0x40000000

#define GPIO3_INST_GPIO_MEM_MAP_NAME      "gpio3_inst_gpio_mem_map"
#define GPIO3_INST_GPIO_MEM_MAP_BASE_ADDR 0x40009000

#define I2C_MST0_INST_I2C_CONTROLLER_MEM_MAP_NAME                              \
	"i2c_mst0_inst_i2c_controller_mem_map"
#define I2C_MST0_INST_I2C_CONTROLLER_MEM_MAP_BASE_ADDR 0x40004000

#define I2C_SLAVE0_INST_I2C_TARGET_MEM_MAP_NAME                                \
	"i2c_slave0_inst_i2c_target_mem_map"
#define I2C_SLAVE0_INST_I2C_TARGET_MEM_MAP_BASE_ADDR 0x40001000

#define SYS_MEM0_INST_AXI4_S0_MODEL_MEM_MAP_NAME                               \
	"sys_mem0_inst_axi4_s0_model_mem_map"
#define SYS_MEM0_INST_AXI4_S0_MODEL_MEM_MAP_BASE_ADDR 0x0

#define UART0_INST_UART_MEM_MAP_NAME                  "uart0_inst_uart_mem_map"
#define UART0_INST_UART_MEM_MAP_BASE_ADDR             0x40002000

#define APB_FEEDTHROUGH0_INST_APB_FEEDTHROUGH_MEM_MAP_NAME                     \
	"apb_feedthrough0_inst_apb_feedthrough_mem_map"
#define APB_FEEDTHROUGH0_INST_APB_FEEDTHROUGH_MEM_MAP_BASE_ADDR 0x40003000

#define APB_FEEDTHROUGH1_INST_APB_FEEDTHROUGH_MEM_MAP_NAME                     \
	"apb_feedthrough1_inst_apb_feedthrough_mem_map"
#define APB_FEEDTHROUGH1_INST_APB_FEEDTHROUGH_MEM_MAP_BASE_ADDR 0x40005000

/* register test (reg_test.c) is to test the accessibility of the design by
accessing the testable register of each IP instance, it might affect the
environment during test. Treat this with care, it's expected to be done only
once when the SOC is generated on fly, and make sure to disable it when
developing the application firmware. */
#define REG_TEST_ENABLE                                         0

/* riscv_rx0_inst parameters */
#define RISCV_RX0_INST_AXI_BASE_ADDR                            0x00000000
#define RISCV_RX0_INST_AXI_BASE_ADDR_INPUT                      00000000
#define RISCV_RX0_INST_AXI_ID_NUM_DATA                          0
#define RISCV_RX0_INST_AXI_ID_NUM_INSTR                         0
#define RISCV_RX0_INST_AXI_ID_WIDTH                             4
#define RISCV_RX0_INST_AXI_REG_TYPE                             0
#define RISCV_RX0_INST_A_EXT                                    True
#define RISCV_RX0_INST_BAUD_RATE                                115200
#define RISCV_RX0_INST_BAUD_RATE_TYPE                           0
#define RISCV_RX0_INST_CACHE_ENABLE                             True
#define RISCV_RX0_INST_CACHE_ENV                                True
#define RISCV_RX0_INST_CACHE_RANGE_HIGH                         40000000
#define RISCV_RX0_INST_CDC_S10                                  False
#define RISCV_RX0_INST_CDC_S11                                  False
#define RISCV_RX0_INST_CDC_S12                                  False
#define RISCV_RX0_INST_CDC_S13                                  False
#define RISCV_RX0_INST_CDC_S14                                  False
#define RISCV_RX0_INST_CDC_S15                                  False
#define RISCV_RX0_INST_CDC_S16                                  False
#define RISCV_RX0_INST_CDC_S17                                  False
#define RISCV_RX0_INST_CDC_S18                                  False
#define RISCV_RX0_INST_CDC_S19                                  False
#define RISCV_RX0_INST_CDC_S2                                   False
#define RISCV_RX0_INST_CDC_S20                                  False
#define RISCV_RX0_INST_CDC_S21                                  False
#define RISCV_RX0_INST_CDC_S22                                  False
#define RISCV_RX0_INST_CDC_S23                                  False
#define RISCV_RX0_INST_CDC_S24                                  False
#define RISCV_RX0_INST_CDC_S25                                  False
#define RISCV_RX0_INST_CDC_S26                                  False
#define RISCV_RX0_INST_CDC_S27                                  False
#define RISCV_RX0_INST_CDC_S28                                  False
#define RISCV_RX0_INST_CDC_S29                                  False
#define RISCV_RX0_INST_CDC_S3                                   False
#define RISCV_RX0_INST_CDC_S30                                  False
#define RISCV_RX0_INST_CDC_S31                                  False
#define RISCV_RX0_INST_CDC_S4                                   False
#define RISCV_RX0_INST_CDC_S5                                   False
#define RISCV_RX0_INST_CDC_S6                                   False
#define RISCV_RX0_INST_CDC_S7                                   False
#define RISCV_RX0_INST_CDC_S8                                   False
#define RISCV_RX0_INST_CDC_S9                                   False
#define RISCV_RX0_INST_CDC_SYNC2                                0b000000000000000000000000000000
#define RISCV_RX0_INST_CFU_EN                                   False
#define RISCV_RX0_INST_CFU_N_CFUS                               1
#define RISCV_RX0_INST_CLINT_EN                                 True
#define RISCV_RX0_INST_CLK_DIVISOR                              868
#define RISCV_RX0_INST_C_EXT                                    True
#define RISCV_RX0_INST_DBUS_WRAPPER                             False
#define RISCV_RX0_INST_DCACHE_ENABLE                            True
#define RISCV_RX0_INST_DCACHE_RANGE_HIGH                        0x40000000
#define RISCV_RX0_INST_DCACHE_RANGE_LOW                         0x00000000
#define RISCV_RX0_INST_DEBUG_ENABLE                             True
#define RISCV_RX0_INST_DEVICE                                   LIFCL
#define RISCV_RX0_INST_F_EXT                                    False
#define RISCV_RX0_INST_HW_WATCHPOINT                            0
#define RISCV_RX0_INST_IBUS_WRAPPER                             False
#define RISCV_RX0_INST_ICACHE_ENABLE                            True
#define RISCV_RX0_INST_ICACHE_RANGE_HIGH                        0x40000000
#define RISCV_RX0_INST_ICACHE_RANGE_LOW                         0x00000000
#define RISCV_RX0_INST_INSTR_PORT_ENABLE                        True
#define RISCV_RX0_INST_IRQ_NMI_EN                               False
#define RISCV_RX0_INST_IRQ_NUM                                  4
#define RISCV_RX0_INST_IRQ_PRIORITY_WIDTH                       3
#define RISCV_RX0_INST_IRQ_SUPERVISOR_EN                        False
#define RISCV_RX0_INST_JTAG_CHANNEL                             14
#define RISCV_RX0_INST_JTAG_CHANNEL_EXTEND                      False
#define RISCV_RX0_INST_JTAG_TYPE                                Hard
#define RISCV_RX0_INST_LCR_DATA_BITS                            8
#define RISCV_RX0_INST_LCR_PARITY_ENABLE                        False
#define RISCV_RX0_INST_LCR_STOP_BITS                            1
#define RISCV_RX0_INST_LOCAL_BUS_BASE_ADDR                      0xFFFFFFFF
#define RISCV_RX0_INST_LOCAL_BUS_BASE_ADDR_INPUT                FFFFFFFF
#define RISCV_RX0_INST_MODE                                     Balanced
#define RISCV_RX0_INST_M_EXT                                    True
#define RISCV_RX0_INST_PLIC_EN                                  True
#define RISCV_RX0_INST_RESET_VECTOR                             0x00000000
#define RISCV_RX0_INST_RESET_VECTOR_INPUT                       00000000
#define RISCV_RX0_INST_RUN_TIME_DEBUG                           False
#define RISCV_RX0_INST_RVFI_EN                                  False
#define RISCV_RX0_INST_SC_BASE_ADDR                             0xFFFFFFFF
#define RISCV_RX0_INST_SOFT_JTAG                                False
#define RISCV_RX0_INST_STANDARD_BAUD_RATE                       115200
#define RISCV_RX0_INST_STDOUT_SIM                               False
#define RISCV_RX0_INST_STDOUT_SIMFAST                           False
#define RISCV_RX0_INST_SYS_CACHE                                False
#define RISCV_RX0_INST_SYS_CACHE_BASE_ADDR_INPUT                FFFFFFFF
#define RISCV_RX0_INST_SYS_CLOCK_FREQ                           100.0
#define RISCV_RX0_INST_TCM_ENABLE                               False
#define RISCV_RX0_INST_UART_EN                                  False
#define RISCV_RX0_INST_UART_SIM_EN                              False

/* gpio0_inst parameters */
#define GPIO0_INST_GPIO_DIRS                                    0x0000001F
#define GPIO0_INST_LINES_NUM                                    5

/* gpio3_inst parameters */
#define GPIO3_INST_GPIO_DIRS                                    0x0043E000
#define GPIO3_INST_LINES_NUM                                    24

/* i2c_mst0_inst parameters */
#define I2C_MST0_INST_ACTUAL_CLOCK_FREQ                         100.20040080160321
#define I2C_MST0_INST_APB_ENABLE                                True
#define I2C_MST0_INST_DESIRED_CLOCK_FREQ                        100.0
#define I2C_MST0_INST_FAMILY                                    LFCPNX
#define I2C_MST0_INST_FIFO_DEPTH                                16
#define I2C_MST0_INST_FIFO_IMPL                                 LUT
#define I2C_MST0_INST_FIFO_WIDTH                                8
#define I2C_MST0_INST_PRESCALER                                 247
#define I2C_MST0_INST_PRESCALER_INPUT                           247
#define I2C_MST0_INST_REMOVE_TRISTATE                           False
#define I2C_MST0_INST_RX_FIFO_AF_FLAG                           14
#define I2C_MST0_INST_SYS_CLOCK_FREQ                            50
#define I2C_MST0_INST_TX_FIFO_AE_FLAG                           2

/* i2c_slave0_inst parameters */
#define I2C_SLAVE0_INST_BASE_ADDR                               I2C_SLAVE0_INST_I2C_TARGET_MEM_MAP_BASE_ADDR
#define I2C_SLAVE0_INST_SLAVE_ADDR                              0x51
#define I2C_SLAVE0_INST_ADDR_MODE                               0x00

/* uart0_inst parameters */
#define UART_INST_BASE_ADDR                                     UART0_INST_UART_MEM_MAP_BASE_ADDR
#define UART0_INST_BAUD_RATE                                    921600
#define UART_INST_BAUD_RATE                                     UART0_INST_BAUD_RATE
#define UART0_INST_DATA_WIDTH                                   8
#define UART0_INST_STOP_BITS                                    1
#define UART0_INST_SYS_CLK                                      50.0
#define UART_INST_SYS_CLK                                       UART0_INST_SYS_CLK

/* apb_feedthrough0_inst parameters */
#define APB_FEEDTHROUGH0_INST_ADDR_SPACE                        4096
#define APB_FEEDTHROUGH0_INST_ADDR_SPACE_STR                    0x1000
#define APB_FEEDTHROUGH0_INST_AS_ADDR_WIDTH                     10
#define APB_FEEDTHROUGH0_INST_DATA_WIDTH                        32
#define APB_FEEDTHROUGH0_INST_INTERFACE_TYPE                    Completer
#define APB_FEEDTHROUGH0_INST_MEM_MAP_STR                       0x1000
#define APB_FEEDTHROUGH0_INST_MM_ADDR_WIDTH                     12
#define APB_FEEDTHROUGH0_INST_M_ADDR_WIDTH                      12
#define APB_FEEDTHROUGH0_INST_PSLVERR_EN                        True

/* apb_feedthrough1_inst parameters */
#define APB_FEEDTHROUGH1_INST_ADDR_SPACE                        4096
#define APB_FEEDTHROUGH1_INST_ADDR_SPACE_STR                    0x1000
#define APB_FEEDTHROUGH1_INST_AS_ADDR_WIDTH                     10
#define APB_FEEDTHROUGH1_INST_DATA_WIDTH                        32
#define APB_FEEDTHROUGH1_INST_INTERFACE_TYPE                    Completer
#define APB_FEEDTHROUGH1_INST_MEM_MAP_STR                       0x1000
#define APB_FEEDTHROUGH1_INST_MM_ADDR_WIDTH                     12
#define APB_FEEDTHROUGH1_INST_M_ADDR_WIDTH                      12
#define APB_FEEDTHROUGH1_INST_PSLVERR_EN                        True

/* interrupt */

#define I2C_SLAVE0_INST_IRQ                                     2
#define GPIO0_INST_IRQ                                          3
#define UART0_INST_IRQ                                          4
#define I2C_MST0_INST_IRQ                                       5

#endif
